Implement `scanItems`
sviridov-alexey/aws-dynamodb-mock pull request #14
Opened 2021-11-24 18:10 UTC by xbreathoflife

Fixes #13

2021-12-01 11:27 UTC, kkarnauk commented on src/main/kotlin/ru/hse/dynamomock/service/AWSDynamoDBMockService.kt
>          val sortKeyAttributeValue = keys[sortKeyName]
Это не относится к текущему PR, но я только сейчас это заметил:
* Почему 339 и 340 строчки не объединить?
* Насколько я знаю `?: return ...` -- моветон. Лучше использовать `?.let`.
* Когда строчка выглядит как `a ?: return null` (338 строка), это странно.
Думаю, на второй пункт можно забить.

2021-12-03 22:59 UTC, xbreathoflife commented on src/main/kotlin/ru/hse/dynamomock/service/AWSDynamoDBMockService.kt
>          val sortKeyAttributeValue = keys[sortKeyName]
А эти строчки вообще можно удалить, оказывается. Потому что если sortKeyName != null, то потом мы должны бросить экспешн, а не вернуть null. Но это проверка как раз делается в getKeyFromMetadata, которая вызывается после.

2021-12-09 16:44 UTC, sviridov-alexey requested changes

2021-12-09 16:44 UTC, sviridov-alexey commented on src/main/kotlin/ru/hse/dynamomock/service/AWSDynamoDBMockService.kt
> +            val info = firstRow.split(";")
Why not use OpenCSV for actual parsing?

2021-12-09 16:44 UTC, sviridov-alexey commented on src/main/kotlin/ru/hse/dynamomock/service/AWSDynamoDBMockService.kt
> +                    throw AWSMockCSVException("Function scanItems supports only S, N, NS, SS, NULL, BOOL types right now")
It's better to use String representation of allowedTypes for info, to consistency between actual tyes and this message

2021-12-09 16:44 UTC, sviridov-alexey commented on src/main/kotlin/ru/hse/dynamomock/service/AWSDynamoDBMockService.kt
> +                val type = value[1].trim()
val (columnName, type) = value.zipWithNext().firstOrNull() ?: throw AWSMockCSVException("Wrong value format. Use <column_name>|<type>")

2021-12-09 16:44 UTC, sviridov-alexey commented on src/main/kotlin/ru/hse/dynamomock/service/AWSDynamoDBMockService.kt
> +        File(fileName).forEachLine {
Why do we need to reopen the file which was opened ten lines before?

2021-12-09 16:44 UTC, sviridov-alexey commented on src/main/kotlin/ru/hse/dynamomock/service/AWSDynamoDBMockService.kt
> +                    throw AWSMockCSVException("${i + 1} row's size doesn't match the size of first row")
I think we should call fist line `header`

2021-12-09 16:44 UTC, sviridov-alexey commented on src/main/kotlin/ru/hse/dynamomock/service/AWSDynamoDBMockService.kt
> +                    columnName to when (DynamoType.valueOf(type)) {
It seems you have become a huge fan of Pairs :) It's OK, especially after Java, like a breath of fresh air

2021-12-09 16:44 UTC, sviridov-alexey commented on src/main/kotlin/ru/hse/dynamomock/service/AWSDynamoDBMockService.kt
> +                        else -> throw AWSMockCSVException("Function scanItems supports only S, N, NS, SS, NULL, BOOL types right now")
Maybe it worth to create additional Enum, like ImporableTypes, and make this `when` full (without else, because we already check this type before)

2021-12-09 16:44 UTC, sviridov-alexey commented on src/main/kotlin/ru/hse/dynamomock/service/AWSDynamoDBMockService.kt
> +        var i = 0
Maybe there is indexed variant of forEachLine?

2021-12-09 16:44 UTC, sviridov-alexey commented on src/main/kotlin/ru/hse/dynamomock/service/AWSDynamoDBMockService.kt
> +        itemsList.forEach {
Why do we do an actual insertion in a separate loop, instead of a file line iteration loop?

2021-12-11 11:49 UTC, xbreathoflife commented on src/main/kotlin/ru/hse/dynamomock/service/AWSDynamoDBMockService.kt
> +            val info = firstRow.split(";")
Rewrote it with kotlin-csv

2021-12-13 12:08 UTC, kkarnauk commented on src/main/kotlin/ru/hse/dynamomock/service/AWSDynamoDBMockService.kt
> +                columnName to when (ImportableType.valueOf(type)) {
Looks like a util function for `ImportableType`. Should we move it to the definition of `ImportableType`? IMHO.

2021-12-13 12:08 UTC, kkarnauk commented on src/main/kotlin/ru/hse/dynamomock/service/AWSDynamoDBMockService.kt
> +            throw DynamoDbException.builder()
`dynamoException` :)

2021-12-16 10:57 UTC, sviridov-alexey commented on src/main/kotlin/ru/hse/dynamomock/service/AWSDynamoDBMockService.kt
> +            readAllAsSequence().forEach { row ->
Обсудить на встрече

2021-12-16 12:48 UTC, sviridov-alexey approved these changes
Please, rename any mentions of 'scan' to import

2021-12-16 16:26 UTC, merged