DML + tests
sviridov-alexey/aws-dynamodb-mock pull request #7
Opened 2021-11-04 00:55 UTC by xbreathoflife

Fixes #3 
Fixes #2

2021-11-04 10:25 UTC, kkarnauk commented on src/main/kotlin/ru/hse/dynamomock/db/ExposedStorage.kt
> +            val table = checkNotNull(tables[request.tableName])
Можно использовать `map.getValue`, чтобы получить `not null`.
В любом случае, `check` кидает `illegalStateException`, хотя по смыслу, если и хочется кидать, то `illegalArgument` (то есть `require`).

2021-11-04 10:25 UTC, kkarnauk commented on src/main/kotlin/ru/hse/dynamomock/service/AWSDynamoDBMockService.kt
> +    fun putItem(request: PutItemRequest): PutItemResponse {
`putItem`, `getItem` и `deleteItem` начинаются очень похоже.

2021-11-04 10:25 UTC, kkarnauk commented on src/main/kotlin/ru/hse/dynamomock/service/AWSDynamoDBMockService.kt
> +        }.toList()
`map` и так возвращает `List`

2021-11-04 10:25 UTC, kkarnauk commented on src/main/kotlin/ru/hse/dynamomock/service/AWSDynamoDBMockService.kt
> +        val partitionKeyAttributeValue = checkNotNull(keys[partitionKeyName])
Лучше `require`, потому что он кидает более подходящий `Exception`.

2021-11-04 10:25 UTC, kkarnauk commented on src/test/kotlin/ru/hse/dynamomock/AWSDynamoDBMockTest.kt
> +        fun generate(): TableMetadata {
Изначально этот метод назывался `generate`, потому что название было `RandomTableMetadataGenerator`. Но теперь `generate` вообще не подходит.

2021-11-04 12:14 UTC, sviridov-alexey requested changes

2021-11-04 12:14 UTC, sviridov-alexey commented on src/test/kotlin/ru/hse/dynamomock/AWSDynamoDBMockDMLTest.kt
> +            assertEquals(item, response.item())
Нормально ли сработает assert если поля записи вернутся в другом порядке?

2021-11-04 12:14 UTC, sviridov-alexey commented on src/test/kotlin/ru/hse/dynamomock/AWSDynamoDBMockDMLTest.kt
> +        repeat(10) {
Зачем мы тестируем это 10 раз?

2021-11-04 12:14 UTC, sviridov-alexey commented on src/test/kotlin/ru/hse/dynamomock/AWSDynamoDBMockDMLTest.kt
> +        repeat(10) {
Почему 10? Может быть лучше 1000, что бы наверняка? :)

2021-11-04 12:14 UTC, sviridov-alexey commented on src/test/kotlin/ru/hse/dynamomock/AWSDynamoDBMockDMLTest.kt
> +            val item = RandomDataGenerator.generateItem(description.attributeDefinitions())
Зачем нам создавать item, ведь для getItem достаточно ключа?

2021-11-04 12:14 UTC, sviridov-alexey commented on src/test/kotlin/ru/hse/dynamomock/AWSDynamoDBMockDMLTest.kt
> +            mock.deleteItem(deleteItemRequestBuilder(description.tableName(), keys))
Неплохо бы перед delete убедиться что item был создан.

2021-11-04 12:37 UTC, xbreathoflife commented on src/main/kotlin/ru/hse/dynamomock/service/AWSDynamoDBMockService.kt
> +        val attributes = when (request.returnValues()) {
Из документации deleteItem: "The ReturnValues parameter is used by several DynamoDB operations; however, DeleteItem does not recognize any values other than NONE or ALL_OLD."

 Но я не уверена, что именно он бросает, если тип не тот. Вроде бы такая же логика в PutItem

2021-11-04 12:44 UTC, xbreathoflife commented on src/test/kotlin/ru/hse/dynamomock/AWSDynamoDBMockDMLTest.kt
> +        repeat(10) {
Вообще видимо лучше тестировать только 1 раз, чтобы вероятность, что ключи совпадут у следующих item'ов равнялась 0

2021-11-04 21:50 UTC, kkarnauk commented on src/main/kotlin/ru/hse/dynamomock/service/AWSDynamoDBMockService.kt
> +import java.lang.IllegalArgumentException
Не то исключение :)
У Котлина свой `IllegalArgumentException`.

2021-11-05 20:12 UTC, kkarnauk commented on src/main/kotlin/ru/hse/dynamomock/db/ExposedStorage.kt
> +        if (sortOp == null) partitionOp else partitionOp and sortOp
Заменяется на `sortOp ?: partitionOp`

2021-11-06 23:36 UTC, kkarnauk commented on src/main/kotlin/ru/hse/dynamomock/db/ExposedStorage.kt
> +        if (sortOp == null) partitionOp else partitionOp and sortOp
Я слепой немного

2021-11-07 10:13 UTC, xbreathoflife commented on src/main/kotlin/ru/hse/dynamomock/db/ExposedStorage.kt
> +                item.addAll(Json.decodeFromString(foundItem[table.attributes]))
Если делаю через `return@transaction Json.decodeFromString(foundItem[table.attributes])`, то тесты начинают все падать(

2021-11-11 12:43 UTC, sviridov-alexey commented on src/main/kotlin/ru/hse/dynamomock/service/AWSDynamoDBMockService.kt
> +            ss = if (value.hasSs()) value.ss() else null,
value.ss().takeIf { value.hasSs() }

2021-11-11 13:03 UTC, sviridov-alexey approved these changes

2021-11-11 13:16 UTC, merged